### ISSUE TITLE
base-4.9 changes

### ISSUE THREAD

**Issue by neongreen** [nikita-volkov/base-prelude#16]
1. New module: `Control.Monad.IO.Class`
2. New modules: `Data.List.NonEmpty` and `Data.Semigroup`
3. New modules: `Data.Functor.Classes`, `Data.Functor.Compose`, `Data.Functor.Product`, and `Data.Functor.Sum`
4. New module: `Control.Monad.Fail`
5. `traceM`, `traceShowM` (which we reimplement) have been generalised to `Applicative` – should we generalise them as well for older versions of base, or not? (I lean towards “not”, because together with #15 it would lead to weirdness – `traceM` would have an `Applicative` constraint when base-4.6 is used, `Monad` when base-4.7 is used, and `Applicative` again when base-4.9 is used.)
6. New function: `forkOSWithUnmask` (could be reimplemented)

**Comment by neongreen** [comment]
I can make a pull request, but first it needs to be decided which of these should go into base-prelude and which shouldn't.

**Comment by nikita-volkov** [comment]
I agree that we need a clearer strategy. 

I believe that we should be reexporting everything we can for each generation of "base". This isn't hard to achieve with CPP. Also I propose to stop reimplementing functions and drop the existing ones due to [thoughts expressed in another thread](https://github.com/nikita-volkov/base-prelude/issues/17#issuecomment-225502165). Since such changes would be quite radical, we'll increment the package version to "2", but first I want to have a discussion for the same reason.

**Comment by neongreen** [comment]
I don't think there's much point in removing them. Compared to base-prelude, base-compat is less convenient to use – by including the reimplemented functions we simply make life easier for some (probably small) number of users, but don't make anything worse for others. Furthermore, reimplemented functions will become more useful once base-prelude gains adoption among library writers (which is something I still hope for).

**Comment by neongreen** [comment]
This said, I don't think we should reimplement each and every function (`forkOSWithUnmask` is probably too specialised to be included).

**Comment by nikita-volkov** [comment]
> I don't think there's much point in removing them.

To make the package's intent clear: a Prelude, which exports all the possible definitions depending on the version of "base".

Reimplementation of symbols for older versions of "base" falls under the compatibility category of problems.

With us removing the reimplementations from "base-prelude", there can appear another package like "base-prelude-compat", which will extend "base-prelude" with the symbols from "base-compat". It'll provide a much richer solution for the legacy GHC versions than what "base-prelude" provides today and will require much less maintenance, because it'll delegate most of the work to the parent packages.

> I don't think we should reimplement each and every function

See, that's the problem. This makes the purpose of "base-prelude" inconsistent, and hence unpredictable for the user.

--

Either way, we can postpone the decision on removing the function reimplementations. For now we can only implement the missing reexports.

**Comment by neongreen** [comment]
> a Prelude, which exports all the possible definitions depending on the version of "base"

That's “how it works”; the intent is usually more high-level. I always perceived the package's intent (or “mission”) as “a Prelude that removes the need to import anything, if all you need is functions from base”. Reimplementing functions provided by newer versions of base seems to be in the spirit of this mission, since e.g. `(&)` is clearly a function from base, and `Data.Function.Compat` is clearly a module that would have to be imported if base-prelude didn't provide `(&)`.

(A comparison: Google searches for words in text of HTML pages, but it doesn't prevent it from also searching for synonyms, showing word etymology, finding locations on maps, and being a currency converter – all of which make Google more useful.)

> and will require much less maintenance

(I'm willing to do the maintenance.)

> and hence unpredictable for the user

I admit I could actually be wrong about all of this, and this *would* be confusing for users. Perhaps we could ask #haskell or some other place where said users could be found. (I just did, actually.)

---

Just in case: despite the amount of bikeshedding I have created around this, I don't actually care and I doubt it's going to influence anyone's life that much. If you feel strongly that they should be removed, by all means, remove them :) I can even submit a pull request.

**Comment by neongreen** [comment]
> For now we can only implement the missing reexports.

I'll make a pull request tomorrow.

**Comment by Tuplanolla** [comment]
This and issue #17 are still unresolved.

**Comment by neongreen** [comment]
This has been resolved but a new version has not been released. @nikita-volkov can you please cut a release?

**Comment by nikita-volkov** [comment]
Done
