### ISSUE TITLE
Missing changes from base-4.8 and 4.7

### ISSUE THREAD

**Issue by neongreen** [nikita-volkov/base-prelude#17]
base-4.8:

* `Numeric.Natural`
* `Data.Void` (moved from void)
* `Data.Functor.Identity` (moved from transformers)

base-4.7:

* `Data.Proxy`
* `Data.Coerce`
* `void` was added (could be reimplemented)
* `isLeft`, `isRight` were added (could be reimplemented)

Should I make a PR?

**Comment by nikita-volkov** [comment]
Sure! Since we're actively using CPP in this project now, we can export even the most recent APIs.

I'm not sure though now, whether there was a good point from the start in reimplementing some functions for the older versions of "base". That made the purpose of the package less specific and introduced more responsibilities, while crossing with the area, which is specifically and much more thoroughly approached by the "base-compat" package. I'm now thinking we should drop the function reimplementations and only focus on the CPP-conditioned reexports. What do you think?

**Comment by nikita-volkov** [comment]
I suggest to continue this discussion in the thread #16.
